core/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    # PaymentView,
    AddCouponView,
    RequestRefundView,
    stripe_config,
    create_checkout_session,
    verify_checkout,
    successView,
    stripe_webhook,
    OrderSnippetView,
    ViewOrders,
    CategoriesView,
    searchposts,
    cancelledView,
    admin_view

)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('adminpanel/' , admin_view , name = 'admin-panel'),
    path('category/<slug:slug>/', CategoriesView, name='category'),

    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    # path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

    path('view-orders/' ,ViewOrders.as_view()  , name='view-orders'),
    path('order-snippet/' , OrderSnippetView.as_view() , name='order-snippet'),
    path('config/', stripe_config),
    path('verify-checkout/', verify_checkout, name='verify-checkout'),
    path('create-checkout-session/',
         create_checkout_session.as_view(), name='create-checkout'),
    path('success/', successView , name='successUrl'),
    path('cancelled/', cancelledView , name='cancelledUrl'),
    path('webhook/', stripe_webhook ),

    path('search/', searchposts, name='search'),


]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('C', 'camera'),
    ('TP', 'tripods'),
    ('FL', 'flashlights'),
    ('MC', 'memoryCards'),
    ('CB' , 'cameraBags'),
    ('B' , 'batteries')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


BADGE_CHOICES = (
    ('New', 'New'),
)

BRAND_CHOICES = (
    ('C' , 'Canon'),
    ('S' , 'Sony'),
    ('N' , 'Nikon'),
    ('F' , 'Fujifilm'),
    ('P' , 'Panasonic'),
    ('O', 'Olympus'),
    ('PX' , 'Pentax'),
    ('IN' ,'Instax'),
)

class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    badge = models.CharField(choices=BADGE_CHOICES , max_length=5 , blank=True , null=True)
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    brand = models.CharField(choices=BRAND_CHOICES , max_length=3)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    # descriptionF = models.TextField()
    # descriptionS = models.TextField(blank = True , null= True)
    # descriptionT = models.TextField(blank = True , null= True)
    descriptionFo = models.TextField(blank = True , null= True)
    image = models.ImageField()
    stripe_key = models.CharField(max_length=200, default='default key')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE , related_name='items')
    quantity = models.IntegerField(default=1)
    ordered_date = models.CharField(max_length=10 , default=None , null=True , blank=True)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return int(self.get_total_item_price() - self.get_total_discount_item_price())

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem , related_name='orders')
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    stripe_charge_id = models.CharField(max_length=50)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <!-- logo font -->
  <link href="https://fonts.googleapis.com/css2?family=Audiowide&display=swap" rel="stylesheet">
  <!-- poppins -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
  <!-- monserraat = card title (item name) -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <script src="https://js.stripe.com/v3/"></script>  
  <script src="{% static 'main.js' %}"></script>

  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

  <div class="cls-tosts position-fixed p-3" style="z-index: 11; bottom: 0; right: 0; min-width: 250px;">
    <div
      id="liveToast"
      class="toast"
      data-autohide="true"
      role="alert"
      aria-live="assertive"
      aria-atomic="true"
      style="background-color: #000; color: #fff;"

    >
      <div class="toast-header" style="background-color: #820000; color:#fff; display: flex; align-items: center; justify-content: space-between;">
        <strong class="me-auto" style="margin-inline-end:50px ;">Cam store</strong>
        <small>just now</small>
      </div>
      <div class="toast-body">
        {% for msg in messages %}
  
        <h6 class="cls-toast-message">{{msg}}</h6>
  
        {% endfor %}
      </div>
    </div>
  </div>

    {% if messages %}
    <script>
      document.getElementById("liveToast").classList.add("show");
      setTimeout(() => {
        document.getElementById("liveToast").classList.remove("show");
      }, 3000);
    </script>

    {% endif %}

    <div class="pt-3">

      {% block content %}
      {% endblock content %}

      {% block extra_body %}
      {% endblock %}

      {% include "footer.html" %}
      {% include "scripts.html" %}

      {% block extra_scripts %}
      {% endblock extra_scripts %}

    </div>
</body>
</html>

templates/footer.html
<footer>
  <div class="footer-content">

    <h3>Who we are</h3>

    <p>We are rapidly emerging digital Camera products sales and marketing subsidiary of Cam store Inc., Cam store India markets a comprehensive range of sophisticated contemporary digital imaging products and solutions in India. In sync with its corporate tagline --<br> ❝ Capture it all ❞  </p>

    <ul class="socials">

      <li><a href="#"><i class="fab fa-facebook"></i></a></li>

      <li><a href="#"><i class="fab fa-twitter"></i></a></li>

      <li><a href="#"><i class="fab fa-google-plus"></i></a></li>

      <li><a href="#"><i class="fab fa-youtube"></i></a></li>

      <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>

    </ul>

  </div>

  <div class="footer-bottom">

    <p style="margin: 0;">Copyright &copy <span id="year"></span> <a href="{% url 'core:home' %}">@Photopark</a> </p>

  </div>

</footer>

templates/home.html
{% extends "base.html" %}


{% block content %}
  <main>

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color mb-5 cls-categories">

        <!-- Navbar brand -->
        <!-- <span class="navbar-brand cls-navbar-brand">Categories:</span> -->

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">

            <!-- {{request.path}} -->
            {% if request.path == '/' %}
              <li class="nav-item active">

            {% else %}
              <li class="nav-item ">

            {% endif %}
              <a class="nav-link" href="{% url 'core:home' %}">All
                <span class="sr-only">(current)</span>
              </a>
            </li>


            {% if request.path == "/category/C/" %}
              <li class="nav-item active">

            {% else %}
              <li class="nav-item">

            {% endif %}
              <a class="nav-link" href="{% url 'core:category' slug='C' %}">Camera</a>
            </li>

            {% if request.path == '/category/TP/' %}
              <li class="nav-item active">

            {% else %}
              <li class="nav-item ">

            {% endif %}              
            <a class="nav-link" href="{% url 'core:category' slug='TP' %}">Tripods</a>
            </li>


            {% if request.path == '/category/FL/' %}
              <li class="nav-item active">

            {% else %}
              <li class="nav-item ">

            {% endif %} 
              <a class="nav-link" href="{% url 'core:category' slug='FL' %}">Flashlights</a>
            </li>


            {% if request.path == '/category/MC/' %}
              <li class="nav-item active">

            {% else %}
              <li class="nav-item ">

            {% endif %} 
              <a class="nav-link" href="{% url 'core:category' slug='MC' %}">Memory cards</a>
            </li>


            {% if request.path == '/category/CB/' %}
              <li class="nav-item active">

            {% else %}
              <li class="nav-item ">

            {% endif %} 
              <a class="nav-link" href="{% url 'core:category' slug='CB' %}">Camera Bags</a>
            </li>

            {% if request.path == '/category/B/' %}
              <li class="nav-item active">

            {% else %}
              <li class="nav-item ">

            {% endif %} 
              <a class="nav-link" href="{% url 'core:category' slug='B' %}">Batteries</a>
            </li>

          </ul>
          <!-- Links -->
          <form class="form-inline" action="{% url 'core:search' %}" method="POST">
            {% csrf_token %}
            <div class="md-form my-0 d-flex align-items-center">
              <div class="form-outline form-white cls-search-form">
                <input type="text" id="forWhite" name="search" class="form-control" />
              </div>
              <button type="submit" class="cls-search-btn"><i class="fas fa-search text-white"></i></button>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <div class="container">

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">
          {% if object_list %}
          {% for item in object_list %}
          <div class="col-lg-4 col-md-6 mb-4">

            <div class="card cls-item-card">

              <div class="cls-card-img view overlay" style="height: 350px;">
               
                <img style="width: 100%; height: 100%; object-fit: cover;"  src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h6>{{ item.get_brand_display }}</h6>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text cls-item-title">{{ item.title }}
                      {%if item.badge != None %}
                      <span class=" cls-card-badge badge badge-pill {{ item.get_label_display }}-color" style="vertical-align: middle; margin-bottom: 3px; font-size: 12px;">{{ item.badge }}</span>
                      {% endif %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold cls-card-price">
                  <strong>₹
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}

          {% else %}

          <div class="empty-state">
            <div class="empty-state__content">
              <div class="empty-state__icon">
                <img src="https://img.freepik.com/free-vector/no-data-concept-illustration_114360-626.jpg?size=626&ext=jpg&ga=GA1.2.879045405.1675969669&semt=ais" alt="">
              </div>
              <div class="empty-state__message">No records has been added yet.</div>
              <div class="empty-state__help">
            
              </div>
            </div>
          </div>
          
          <!-- <div class="credit">Illustration by <a href="https://icons8.com/" target="_blank">ICONS8</a>.</div> -->

          {% endif %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container-fluid">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="cls-logo blue-text">Photopark</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} 
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item mr-3">
            <a href="#" class="nav-link waves-effect" style="pointer-events:none;">
              <span class="clearfix d-none d-sm-inline-block"> Welcome {{ request.user }} </span>
            </a>
          </li>
          {% if request.user.is_superuser %}
          <li class="nav-item mr-3">
            <a href="{%  url 'core:admin-panel' %}" class="nav-link waves-effect">
              <!-- <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span> -->
              <!-- <i class="fas fa-shopping-cart"></i> -->
              <span class="clearfix d-none d-sm-inline-block"> Admin panel </span>
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'core:view-orders' %}" class="nav-link waves-effect">
              <!-- <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span> -->
              <!-- <i class="fas fa-shopping-cart"></i> -->
              <span class="clearfix d-none d-sm-inline-block"> Orders </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
              <i class="fas fa-sign-out-alt"></i>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
              <i class="fas fa-sign-in-alt"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup <i class="fas fa-user-plus"></i></span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center ">
    <span class="text-muted h5 mb-0">Your cart</span>
    <span class="badge grey badge-pill" style="font-size: 12px;">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-2 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div style="padding-inline-end : 20px;">
        <h6 class="my-0"><strong style="font-weight: 900;">{{ order_item.quantity }} x</strong> {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted" style="font-family: Montserrat;">₹{{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    <!-- {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success" style="font-family: Montserrat;">₹{{ order.coupon.amount }}</span>
    </li>
    {% endif %} -->
    <li class="list-group-item d-flex justify-content-between">
        <span style="">Total (IN)</span>
        <strong style="font-family: Montserrat; font-size: 18px; font-weight: 700;">₹ {{ order.get_total }}</strong>
    </li>
    </ul>

    <!-- {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-danger btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %} -->

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main class="" style="margin-bottom: 130px;">
    <div class="container ">

    <div class="table-responsive text-nowrap pt-5">
    <h2>Cart</h2>
    {% if object.items.all %}
    <table class="table ">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Gross Price</th>
            <th scope="col">Net Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td style="font-family: Monserrat;font-size: 16px;">₹ {{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td style="font-family: Monserrat;font-size: 16px;">₹ {{ order_item.get_total_item_price }}</td>
            <td style="    display: flex;
            align-items: center;
            justify-content: space-between;
            font-family: Montserrat;
            font-size: 16px;
        ">
            {% if order_item.item.discount_price %}
                ₹ {{ order_item.get_total_discount_item_price }}
                <span class="badge grey ml-2 p-2">Saving ₹ {{ order_item.get_amount_saved }}</span>
            {% else %}
                ₹ {{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash"></i>
            </a>
            </td>
        </tr>
        
        {% endfor %}
        <!-- {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td style="font-family: Montserrat;"><b>-₹ {{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %} -->
       
        {% if object.items.all %}
            {% if object.get_total %}
        <tr>
            <td colspan="5" style="font-size: 16px; font-weight: 700;"><b>Order Total</b></td>
            <td style="font-family: Montserrat; font-size: 18px; font-weight: 700;"><b>₹ {{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="6">
            <a class='btn btn-primary  float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-danger float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
            {% endif %}
        {% endif %}
        </tbody>
    </table>
    {% else %}
    
    <div>
         <div class="empty-state">
        <div class="empty-state__content">
          <div class="empty-state__icon">
            <img src="https://img.freepik.com/free-vector/no-data-concept-illustration_114360-626.jpg?size=626&ext=jpg&ga=GA1.2.879045405.1675969669&semt=ais" alt="">
          </div>
          <div class="empty-state__message">No products has been added yet.</div>
          <div class="empty-state__help">
        
          </div>
        </div>
      </div>
    </div>
    <div class="text-center">
        <a class='btn btn-primary ' style="color: aliceblue;" href='/'>Return to Shop</a>
    </div>
    {% endif %}
    

    </div>

    </div>
  </main>

{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>